# Generated by Django 2.1.3 on 2019-02-12 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('slug', models.SlugField(unique=True)),
                ('layout', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard',
            },
        ),
        migrations.CreateModel(
            name='DashboardItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gadget', models.TextField()),
                ('column_number', models.IntegerField()),
                ('position', models.IntegerField()),
                ('colour', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('collapsed', models.BooleanField()),
                ('modifier', models.TextField(null=True)),
                ('active', models.BooleanField()),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Dashboard')),
            ],
            options={
                'db_table': 'dashboard_item',
            },
        ),
        migrations.AlterUniqueTogether(
            name='dashboard',
            unique_together={('name', 'user')},
        ),
    ]
